### ISSUE TITLE
Client crashes upon opening the creative inventory with guimove enabled

### ISSUE THREAD

**Issue by The-Nyla** [Declipsonator/Meteor-Tweaks#2] opened 2022-01-18 15:16 UTC
crash log:

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 1/18/22, 10:14 AM
Description: Unexpected error

java.lang.IncompatibleClassChangeError: Expected instance not static method 'int meteordevelopment.meteorclient.mixin.CreativeInventoryScreenAccessor.getSelectedTab()'
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.18)
	at me.declipsonator.meteortweaks.modules.GUIMove.skip(GUIMove.java:166)
	at me.declipsonator.meteortweaks.modules.GUIMove.onTick(GUIMove.java:119)
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83)
	at meteordevelopment.orbit.EventBus.post(EventBus.java:47)
	at net.minecraft.client.MinecraftClient.handler$bmb000$onPreTick(MinecraftClient:22546)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1086)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:733)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.client.MinecraftClient.modify$cho000$atTheEndOfSecondCatchBeforePrintingCrashReport(MinecraftClient:17546)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:760)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.client.MinecraftClient.modify$cho000$atTheEndOfSecondCatchBeforePrintingCrashReport(MinecraftClient:17546)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:760)
	at net.minecraft.client.main.Main.main(Main:238)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.declipsonator.meteortweaks.modules.GUIMove.skip(GUIMove.java:166)
	at me.declipsonator.meteortweaks.modules.GUIMove.onTick(GUIMove.java:119)
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83)
	at meteordevelopment.orbit.EventBus.post(EventBus.java:47)
	at net.minecraft.class_310.handler$bmb000$onPreTick(class_310.java:22546)

-- Affected level --
Details:
	All players: 1 total; [class_746['BookWyrm_'/1049, l='ClientLevel', x=1072.70, y=98.00, z=742.94]]
	Chunk stats: 1024, 157
	Level dimension: minecraft:the_nether
	Level spawn location: World: (0,40,0), Section: (at 0,8,0 in 0,2,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 119889 game time, 1463889 day time
	Server brand: Purpur
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:757)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$cho000$atTheEndOfSecondCatchBeforePrintingCrashReport(class_310.java:17546)
	at net.minecraft.class_310.method_1514(class_310.java:760)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$cho000$atTheEndOfSecondCatchBeforePrintingCrashReport(class_310.java:17546)
	at net.minecraft.class_310.method_1514(class_310.java:760)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, continuity/default, continuity/glass_pane_culling_fix, 1.18.zip

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 252080496 bytes (240 MiB) / 1149239296 bytes (1096 MiB) up to 15401484288 bytes (14688 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3400G with Radeon Vega Graphics    
	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
	Microarchitecture: Zen / Zen+
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: spacedesk Graphics Adapter
	Graphics card #0 vendor: datronicsoft
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=1.1.334.150
	Graphics card #1 name: Radeon RX 590 Series
	Graphics card #1 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x67df
	Graphics card #1 versionInfo: DriverVersion=27.20.22001.14011
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37562.68
	Virtual memory used (MB): 13765.46
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 0.00
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx14688m -Xms256m
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.5.4
		advancedchatcore: AdvancedChatCore 1.3.3-1.18
		advancedchatfilters: AdvancedChatFilters 1.1.1
		appleskin: AppleSkin mc1.18-2.2.0
		architectury: Architectury 3.4.9
		baritone: Baritone 1.18-SNAPSHOT
		bedrockminer: Bedrock Miner 1.0.0
		better_clicker: BetterClicker 1.3.0
		betterf3: BetterF3 1.2.2
		blue_endless_jankson: jankson 1.2.1
		caffeineconfig: CaffeineConfig 1.0.0
		cem: Custom Entity Models 0.7.0
		cleancut: CleanCut 1.18-4.0-fabric
		clientarguments: clientarguments b1.1.4
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.1.48
		clumps: Clumps 8.0.4
		com_electronwill_night-config_core: core 3.6.5
		com_electronwill_night-config_toml: toml 3.6.5
		com_github_hube12_seed: SEED master-SNAPSHOT
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_seedfinding_latticg: latticg 1.6
		com_seedfinding_mc_biome: mc_biome b2271807a047bb43ac60c8c20ad47e315f19b9a6
		com_seedfinding_mc_core: mc_core 88b246597e0147e37b38d1b33e9526e6c3eb1469
		com_seedfinding_mc_feature: mc_feature ef939c0dd7d66ab1bd290d6aab1e42a12cb3dbf1
		com_seedfinding_mc_math: mc_math 0eb505174da8a92550f8ec6efe254e0fa936cc0d
		com_seedfinding_mc_noise: mc_noise a6ab8e6c688491829f8d2adf845392da22ef8e9c
		com_seedfinding_mc_reversal: mc_reversal 2.0.0
		com_seedfinding_mc_seed: mc_seed 5518e3ba3ee567fb0b51c15958967f70a6a19e02
		com_seedfinding_mc_terrain: mc_terrain 9e937ddb838e28e79423c287fa18b1ce66f061d7
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		continuity: Continuity 1.0.3+1.18
		controlling: Controlling For Fabric 9.0.11
		cullleaves: Cull Leaves 2.3.2
		deathlog: DeathLog 0.2.6+1.18
		draggable-resource-packs: Draggable Resource Packs 2.0.0
		dynamicfps: Dynamic FPS 2.1.0
		enhancedblockentities: Enhanced Block Entities 0.5+1.18
		entityculling: EntityCulling-Fabric 1.3.3
		experiencebugfix: Experience Bug Fix 18
		extremesoundmuffler: Extreme sound muffler 3.22_fabric-1.18.1
		fabric: Fabric API 0.46.1+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cd65
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.0+17be577f65
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a965
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d9565
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c665
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73d65
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.9+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378a65
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f1765
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cd65
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d9565
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f365
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cd65
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca33565
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d9565
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d9565
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.8+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d9565
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d9565
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.1+3b82842e65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.9+3ac43d9565
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1ac65
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.0+befed49e65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.10+b0b66fc365
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.13+b0b66fc365
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d765
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378a65
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.1+13eda06565
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d9565
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d9565
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d9565
		fabric-structure-api-v1: Fabric Structure API (v1) 2.1.0+0a73a6c265
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d9565
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.5+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.6+b4f4f6cd65
		fabricloader: Fabric Loader 0.12.12
		ferritecore: FerriteCore 4.0.0
		fiber: fiber 0.23.0-2
		ias: In-Game Account Switcher 7.1.3
		ibeeditor: IBE Editor 2.0.10
		indium: Indium 1.0.2-alpha2+mc1.18.1
		instakillma: InstaKill 1.0.1
		io_github_maowimpl_owo: owo 2.0.0
		iris: Iris 1.1.5
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.1.6
		lambdabettergrass: LambdaBetterGrass 1.2.2+1.17
		lambdynlights: LambDynamicLights 2.1.0+1.17
		lazydfu: LazyDFU 0.1.2
		libgui: LibGui 5.0.0-beta.2+1.18-rc1
		libninepatch: LibNinePatch 1.1.0
		libzoomer: LibZoomer 0.3.0+1.17.1
		litematica: Litematica 0.9.0
		malilib: MaLiLib 0.10.0-dev.26
		meteor-additions: MeteorAdditions 1.1.1
		meteor-client: Meteor Client 0.4.7-1401
		meteor-rejects: Meteor Rejects 0.1
		meteor-tweaks: Meteor Tweaks 1.0.6
		meteor-utils: meteor-utils 1.0
		midnightlib: MidnightLib 0.3.1
		minecraft: Minecraft 1.18.1
		modmenu: Mod Menu 3.0.1
		mousetweaks: Mouse Tweaks 2.22
		multiconnect: MultiConnect 1.5.10
		multiconnect-api: MultiConnect API 1.5.10
		multiple-server-lists: Multiple Server Lists 2.0.1
		nicephore: Nicephore fabric-1.18.x-1.1.1
		nimble: Nimble 2.1.1
		notenoughcrashes: Not Enough Crashes 4.1.4+1.18.1
		notes: Notes 1.0.10
		notifications-addon: Notifications Addon 1.0.1
		okzoomer: Ok Zoomer 5.0.0-beta.3+1.17.1
		org_anarres_jcpp: jcpp 1.4.14
		org_javadelight_delight-nashorn-sandbox: delight-nashorn-sandbox 0.2.5
		org_joml_joml: joml 1.10.2
		org_openjdk_nashorn_nashorn-core: nashorn-core 15.3
		org_quiltmc_quilt-json5: quilt-json5 1.0.0
		org_slf4j_slf4j-api: slf4j-api 1.7.25
		org_webjars_bower_js-beautify: js-beautify 1.9.0
		orion: Orion 0.1
		pride: Pride Lib 1.1.0+1.17
		puzzle: Puzzle 1.1.0
		puzzle-base: Puzzle Base 1.1.0
		puzzle-emissives: Puzzle Emissive Textures 1.1.0
		puzzle-gui: Puzzle GUI 1.1.0
		puzzle-models: Puzzle Models 1.1.0
		puzzle-splashscreen: Puzzle Splash Screen 1.1.0
		rebind_all_the_keys: RebindAllTheKeys 1.1.1+1.18
		reeses-sodium-options: Reese's Sodium Options 1.3.0
		roughlyenoughitems: Roughly Enough Items 7.1.390
		searchablecontainers: Searchable Containers 1.3
		seedcrackerx: SeedCrackerX 2.11.4
		seedcrackerx-api: SeedCrackerX API 1.0
		seedmapper: SeedMapper b1.4.7
		smoothcoasters: SmoothCoasters 1.18.1-v1
		sodium: Sodium 0.4.0-alpha6+build.14
		sodium-extra: Sodium Extra 0.3.8
		spruceui: SpruceUI 3.3.2+1.17
		sspb: Sodium Shadowy Path Blocks 0.2.1
		starlight: Starlight 1.0.1+fabric.0583973
		stendhal: Stendhal 1.2.0-1.18
		strongholdfinder: Stronghold Finder 0.0.4
		vector-addon: Vector Addon 0.2.7
		xaerominimap: Xaero's Minimap 21.23.1
		xaeroworldmap: Xaero's World Map 1.19.1
	Launched Version: fabric-loader-0.12.12-1.18.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Radeon RX 590 Series GL version 3.2.14739 Core Profile Forward-Compatible Context 21.6.1 27.20.22001.14011, ATI Technologies Inc.
	Window size: 1920x1017
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, Fabric Mods, continuity/default, continuity/glass_pane_culling_fix, file/1.18.zip
	Current Language: English (US)
	CPU: 8x AMD Ryzen 5 3400G with Radeon Vega Graphics 
	Client Crashes Since Restart: 3
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Meteor Client (meteor-client), Fabric Loader (fabricloader), Meteor Tweaks (meteor-tweaks), Not Enough Crashes (notenoughcrashes)

-- Meteor Client --
Version: 0.4.7
Dev Build: 1401

[Combat]:
auto-armor
auto-totem
criticals
InstaKill
kill-aura

[Player]:
anti-hunger
portals
speed-mine

[Movement]:
anti-levitation
boat-fly
entity-control
gui-move
no-fall
no-slow

[Render]:
better-tooltips
block-selection
break-indicators
entity-owner
esp
fullbright
logout-spots
no-render
storage-esp
tracers
trajectories

[World]:
anti-cactus
build-height
enderman-look
mount-bypass

[Misc]:
auto-reconnect
better-chat
better-tab
inventory-tweaks
middle-click-friend
vanilla-spoof

[Rejects]:
Rendering

[meteor-utils]:
advenced-tooltips
no-pause-on-lost-focus
No-Portal-Hitbox

[Orion]:
nametags-plus

**Comment by Declipsonator** [comment] 2022-01-18 20:41
Does this only happen when meteor tweaks is running?

**Comment by Declipsonator** [comment] 2022-01-18 22:30
I can't reproduce this

**Comment by The-Nyla** [comment] 2022-01-18 22:34
yes, this does only happen when meteor tweaks is present

**Comment by Declipsonator** [comment] 2022-01-18 23:14
Aight

**Comment by Declipsonator** [comment] 2022-01-19 02:16
Can you try running it without the other addons

**Comment by Declipsonator** [comment] 2022-01-23 14:26
@BookWyrm114 I will release a new version within the next day or two. It should fix this, what seemed to be the problem was out of date dependencies in intellij.

**Comment by Declipsonator** [comment] 2022-01-23 16:53
Fixed in https://github.com/Declipsonator/Meteor-Tweaks/releases/tag/v1.1.0

**Closed as completed by Declipsonator** 2022-01-23 16:53 UTC
Labels: bug
